let data = [
  {id: 1, name: "Generic Steel Chips", price: 151.67, store: "99 Ranch Market", free_return_days: 14},
  {id: 2, name: "Handcrafted Metal Bike", price: 122.87, store: "Best Buy", free_return_days: 5},
  {id: 3, name: "Handcrafted Concrete Ball", price: 11.33, store: "Boxed", free_return_days: 13},
  {id: 4, name: "Fantastic Concrete Fish", price: 114.98, store: "99 Ranch Market", free_return_days: 13},
  {id: 5, name: "Unbranded Metal Mouse", price: 14.52, store: "Bargains N More", free_return_days: 10},
  {id: 6, name: "Handmade Wooden Bacon", price: 229.81, store: "Target", free_return_days: 17},
  {id: 7, name: "Small Granite Fish", price: 98.57, store: "Bargains N More", free_return_days: 16},
  {id: 8, name: "Intelligent Concrete Gloves", price: 65.78, store: "Yobys", free_return_days: 7},
  {id: 9, name: "Licensed Plastic Keyboard", price: 53.48, store: "Best Buy", free_return_days: 16},
  {id: 10, name: "Gorgeous Metal Keyboard", price: 91.32, store: "Target", free_return_days: 15},
  {id: 11, name: "Fantastic Fresh Gloves", price: 226.09, store: "Target", free_return_days: 10},
  {id: 12, name: "Handcrafted Frozen Shoes", price: 198.83, store: "Target", free_return_days: 14},
  {id: 13, name: "Handcrafted Granite Chips", price: 88.42, store: "Best Buy", free_return_days: 15},
  {id: 14, name: "Refined Steel Chips", price: 40.5, store: "Overstock", free_return_days: 11},
  {id: 15, name: "Incredible Steel Towels", price: 123.75, store: "Overstock", free_return_days: 14},
  {id: 16, name: "Incredible Granite Car", price: 179.14, store: "Yobys", free_return_days: 6},
  {id: 17, name: "Gorgeous Rubber Salad", price: 12.13, store: "Target", free_return_days: 13},
  {id: 18, name: "Rustic Granite Bike", price: 95.74, store: "Target", free_return_days: 14},
  {id: 19, name: "Handmade Fresh Hat", price: 169.11, store: "Bargains N More", free_return_days: 14},
  {id: 20, name: "Tasty Plastic Cheese", price: 241.62, store: "Best Buy", free_return_days: 8},
  {id: 21, name: "Intelligent Soft Computer", price: 51.45, store: "Boxed", free_return_days: 11},
  {id: 22, name: "Refined Concrete Fish", price: 26.75, store: "Boxed", free_return_days: 14},
  {id: 23, name: "Sleek Cotton Soap", price: 53.12, store: "99 Ranch Market", free_return_days: 14},
  {id: 24, name: "Generic Fresh Bacon", price: 241.7, store: "Target", free_return_days: 13},
  {id: 25, name: "Gorgeous Wooden Salad", price: 193.58, store: "Yobys", free_return_days: 15},
  {id: 26, name: "Handcrafted Wooden Chair", price: 234.83, store: "Target", free_return_days: 15},
  {id: 27, name: "Licensed Steel Ball", price: 205.96, store: "Overstock", free_return_days: 15},
  {id: 28, name: "Incredible Rubber Chair", price: 90.48, store: "Yobys", free_return_days: 8},
  {id: 29, name: "Ergonomic Concrete Shirt", price: 101.33, store: "Yobys", free_return_days: 12},
  {id: 30, name: "Practical Wooden Shirt", price: 59.05, store: "99 Ranch Market", free_return_days: 12},
  {id: 31, name: "Gorgeous Metal Pizza", price: 7.03, store: "Bargains N More", free_return_days: 9},
  {id: 32, name: "Handmade Plastic Ball", price: 106.36, store: "Costco", free_return_days: 10},
  {id: 33, name: "Handcrafted Plastic Tuna", price: 209.65, store: "Bargains N More", free_return_days: 10},
  {id: 34, name: "Intelligent Cotton Cheese", price: 245.83, store: "Best Buy", free_return_days: 17},
  {id: 35, name: "Refined Cotton Chips", price: 36.33, store: "Google Store", free_return_days: 4},
  {id: 36, name: "Handcrafted Soft Keyboard", price: 133.2, store: "Google Store", free_return_days: 6},
  {id: 37, name: "Tasty Rubber Cheese", price: 73.34, store: "99 Ranch Market", free_return_days: 12},
  {id: 38, name: "Sleek Soft Chair", price: 220.51, store: "Best Buy", free_return_days: 16},
  {id: 39, name: "Gorgeous Cotton Table", price: 29.08, store: "Bargains N More", free_return_days: 9},
  {id: 40, name: "Small Cotton Sausages", price: 85.41, store: "Costco", free_return_days: 6},
  {id: 41, name: "Licensed Plastic Bike", price: 49.74, store: "Boxed", free_return_days: 9},
  {id: 42, name: "Licensed Wooden Gloves", price: 204.14, store: "Costco", free_return_days: 12},
  {id: 43, name: "Gorgeous Granite Chair", price: 216.15, store: "Best Buy", free_return_days: 8},
  {id: 44, name: "Tasty Frozen Chicken", price: 177.62, store: "Best Buy", free_return_days: 9},
  {id: 45, name: "Incredible Wooden Tuna", price: 58.05, store: "Best Buy", free_return_days: 12},
  {id: 46, name: "Awesome Soft Hat", price: 208.61, store: "Bargains N More", free_return_days: 7},
  {id: 47, name: "Tasty Steel Ball", price: 194.58, store: "Target", free_return_days: 15},
  {id: 48, name: "Sleek Fresh Shirt", price: 212.91, store: "Bargains N More", free_return_days: 14},
  {id: 49, name: "Refined Granite Hat", price: 19.98, store: "Yobys", free_return_days: 14},
  {id: 50, name: "Refined Frozen Gloves", price: 236.76, store: "Target", free_return_days: 10},
  {id: 51, name: "Refined Steel Bike", price: 56.14, store: "Target", free_return_days: 8},
  {id: 52, name: "Incredible Cotton Keyboard", price: 202.09, store: "Overstock", free_return_days: 16},
  {id: 53, name: "Handmade Metal Shirt", price: 8.38, store: "Overstock", free_return_days: 4},
  {id: 54, name: "Handcrafted Metal Towels", price: 15.46, store: "Yobys", free_return_days: 12},
  {id: 55, name: "Rustic Rubber Hat", price: 228.81, store: "Costco", free_return_days: 14},
  {id: 56, name: "Rustic Soft Bacon", price: 133.5, store: "Google Store", free_return_days: 16},
  {id: 57, name: "Sleek Granite Table", price: 66.15, store: "Boxed", free_return_days: 5},
  {id: 58, name: "Intelligent Granite Table", price: 186, store: "Best Buy", free_return_days: 15},
  {id: 59, name: "Licensed Steel Shoes", price: 125.73, store: "Target", free_return_days: 11},
  {id: 60, name: "Refined Wooden Gloves", price: 170.18, store: "Target", free_return_days: 14},
  {id: 61, name: "Generic Soft Chicken", price: 135.85, store: "Boxed", free_return_days: 5},
  {id: 62, name: "Handmade Concrete Table", price: 8.95, store: "Costco", free_return_days: 12},
  {id: 63, name: "Tasty Steel Chair", price: 218.39, store: "Google Store", free_return_days: 12},
  {id: 64, name: "Incredible Granite Towels", price: 203.53, store: "99 Ranch Market", free_return_days: 13},
  {id: 65, name: "Handcrafted Fresh Fish", price: 51.72, store: "Costco", free_return_days: 14},
  {id: 66, name: "Sleek Steel Pants", price: 115.06, store: "Overstock", free_return_days: 4},
  {id: 67, name: "Tasty Granite Chair", price: 125.52, store: "Costco", free_return_days: 9},
  {id: 68, name: "Unbranded Granite Pizza", price: 76.81, store: "Target", free_return_days: 17},
  {id: 69, name: "Sleek Fresh Pizza", price: 94.22, store: "Overstock", free_return_days: 9},
  {id: 70, name: "Practical Steel Mouse", price: 133.54, store: "Costco", free_return_days: 15},
  {id: 71, name: "Sleek Metal Sausages", price: 222.31, store: "Best Buy", free_return_days: 4},
  {id: 72, name: "Handcrafted Concrete Hat", price: 188.28, store: "Overstock", free_return_days: 7},
  {id: 73, name: "Unbranded Concrete Soap", price: 199.84, store: "99 Ranch Market", free_return_days: 5},
  {id: 74, name: "Generic Wooden Shoes", price: 62.77, store: "Best Buy", free_return_days: 16},
  {id: 75, name: "Awesome Rubber Gloves", price: 243.08, store: "99 Ranch Market", free_return_days: 4},
  {id: 76, name: "Sleek Rubber Soap", price: 88.3, store: "Yobys", free_return_days: 14},
  {id: 77, name: "Licensed Fresh Chips", price: 176.57, store: "Best Buy", free_return_days: 11},
  {id: 78, name: "Tasty Soft Mouse", price: 122.51, store: "Best Buy", free_return_days: 10},
  {id: 79, name: "Unbranded Wooden Car", price: 197.96, store: "Google Store", free_return_days: 7},
  {id: 80, name: "Incredible Frozen Mouse", price: 26.26, store: "Bargains N More", free_return_days: 14},
  {id: 81, name: "Licensed Steel Tuna", price: 167.27, store: "Costco", free_return_days: 10},
  {id: 82, name: "Practical Cotton Shirt", price: 206.9, store: "Costco", free_return_days: 5},
  {id: 83, name: "Refined Rubber Chicken", price: 11.37, store: "Boxed", free_return_days: 10},
  {id: 84, name: "Unbranded Concrete Chicken", price: 155.28, store: "Google Store", free_return_days: 10},
  {id: 85, name: "Rustic Plastic Soap", price: 166.16, store: "Overstock", free_return_days: 6},
  {id: 86, name: "Intelligent Steel Fish", price: 148.38, store: "Google Store", free_return_days: 15},
  {id: 87, name: "Refined Concrete Cheese", price: 89.93, store: "Yobys", free_return_days: 10},
  {id: 88, name: "Fantastic Steel Soap", price: 150.46, store: "Costco", free_return_days: 5},
  {id: 89, name: "Fantastic Steel Soap", price: 147.57, store: "Bargains N More", free_return_days: 5},
  {id: 90, name: "Handcrafted Cotton Ball", price: 210.22, store: "Best Buy", free_return_days: 6},
  {id: 91, name: "Incredible Frozen Pizza", price: 38.15, store: "Best Buy", free_return_days: 14},
  {id: 92, name: "Sleek Fresh Pants", price: 80.71, store: "Overstock", free_return_days: 10},
  {id: 93, name: "Sleek Fresh Pants", price: 90.71, store: "Yobys", free_return_days: 12},
  {id: 94, name: "Rustic Plastic Computer", price: 219.75, store: "Overstock", free_return_days: 15},
  {id: 95, name: "Rustic Plastic Computer", price: 89.01, store: "Best Buy", free_return_days: 10},
  {id: 96, name: "Small Steel Shoes", price: 162.32, store: "Target", free_return_days: 17},
  {id: 97, name: "Small Steel Shoes", price: 86.47, store: "Bargains N More", free_return_days: 11},
  {id: 98, name: "Unbranded Granite Car", price: 195.31, store: "Google Store", free_return_days: 13},
  {id: 99, name: "Unbranded Granite Car", price: 200.47, store: "Overstock", free_return_days: 17},
  {id: 100, name: "Unbranded Granite Car", price: 190.50, store: "Costco", free_return_days: 15}
]

module.exports.data = data;