# version: "3"

# services:
#   results:
#     build: .
#     # image: senwlu/checkout_fec:checkout-swl_results
#     depends_on:
#       - 'database'
#     ports:
#       - '3002:3002'

#   database:
#     image: mysql:5.7
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USER: root



version: '3'
services:
  web:
    build: .
    ports:
      - "3002:3002"